[package]
name = "rust-self-signed-certificate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-ext = "0.0.1"
openssl = { version="0.10.42", features = ["vendored"] }